version: '2'

services:
  mydns-directip-agent:
    image: nobiki/mydns-directip-agent:latest
    environment:
      - VERSION=IPV4ADDR
      - MYDNS_URL=http://www.mydns.jp/directip.html
      - MYDNS_ID=[YOUR_MID]
      - MYDNS_PW=[YOUR_PASSWORD]
    restart: always
    tty: true

